# Setup a Pachyderm development machine. Includes all required dependencies
# such as libgit2 and docker as well as extra utility packages like screen(1)
---
- hosts: tag_dev
  roles:
    - resmo.fail2ban
    - joshualund.golang
    - franklinkim.docker-compose
    - docker
    - { role: docker-gc, docker_gc_frequency: "daily" }
    - dev-extra
    - google-cloud-sdk
    - { role: dev-gcloud, gcloud_snapshot_frequency: "daily" }
    - deb-build
